Rename package to enable Fastly CLI v4
fastly/compute-starter-kit-rust-default pull request #55
Opened 2022-09-29 14:14 UTC by Integralist

The next release of the Fastly CLI will require all Rust starter kits to use the same package name.

2022-09-29 14:23 UTC, chrispoole643 approved these changes
LGTM 🚀

2022-09-29 18:15 UTC, acfoltzer requested changes
Can you regenerate the Cargo.lock file before we merge?

2022-09-29 18:28 UTC, Integralist commented
@acfoltzer will do! thanks for the heads up.

2022-09-29 19:33 UTC, acfoltzer commented
FWIW adding `--locked` to all `cargo` invocations in the CI script will detect if the lockfile is out of date. Another way is to record the hash of the lockfile before running any `cargo` commands, and compare it against the hash at the end of the build to ensure it doesn't change.

It's not the biggest deal in the world, but will hopefully prevent our customers from having dirty git trees as soon as they build the starter kits 🤞🏻

2022-10-03 16:41 UTC, acfoltzer approved these changes

2022-10-04 15:34 UTC, merged